development: &default
  adapter: postgresql
  database: Hypertube_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  timeout: 5000


docker:
  adapter: postgresql
  encoding: unicode
  database: Hypertube_docker
  pool: 5
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: Hypertube_test

production:
  <<: *default
  database: hypertube_production
